const MAX_TITLE_LENGTH = 50;
const MAX_CATEGORY_NAME_LENGTH = 50;
const MAX_TAG_NAME_LENGTH = 30;
const MAX_TAGS_PER_TODO = 10;

module.exports = {
  MAX_TITLE_LENGTH,
  MAX_CATEGORY_NAME_LENGTH,
  MAX_TAG_NAME_LENGTH,
  MAX_TAGS_PER_TODO,
};
